version: '3'
services:
  company:
    container_name: company
    depends_on:
      - companyDb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - "companyDb"
    restart: always
  companyDb:
    container_name: companyDb
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres