server:
  port: 8080

spring:
  application:
    name: company

  datasource:
    url: jdbc:postgresql://companyDb:5432/postgres
#    url: jdbc:postgresql://127.0.0.1:5432/company
    username: postgres
    password: root
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/database/project-changelogs.xml

  security:
    jwt:
      header: Authorization
      secret: N4b654TZN
      expiration: 900000
      token-time: 1
      refresh-token-time: 200

logging:
  level:
    org:
      apache:
        http:
          wire: ERROR